### ISSUE TITLE
binderbot timeout

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-gallery/binderbot#4]
In https://github.com/TomAugspurger/pangeo-dask-gateway/runs/553103921?check_suite_focus=true

```
2020-04-01T20:15:31.0460523Z /opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/binderbot/cli.py:14: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
2020-04-01T20:15:31.0461004Z 2020-04-01 20:15.30 Binder: Waiting on event stream (phase: building) action=binder-start phase=event-stream
2020-04-01T20:15:31.0461487Z   f = asyncio.coroutine(f)
2020-04-01T20:15:31.0461912Z 2020-04-01 20:15.30 Binder: Waiting on event stream (phase: building) action=binder-start phase=event-stream
2020-04-01T20:15:31.0462255Z Traceback (most recent call last):
2020-04-01T20:15:31.0462642Z 2020-04-01 20:15.30 Binder: Waiting on event stream (phase: building) action=binder-start phase=event-stream
2020-04-01T20:15:31.0463856Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/runpy.py", line 193, in _run_module_as_main
2020-04-01T20:15:31.0464326Z 2020-04-01 20:15.30 Binder: Waiting on event stream (phase: building) action=binder-start phase=event-stream
2020-04-01T20:15:31.0464726Z     return _run_code(code, main_globals, None,
2020-04-01T20:15:31.0465118Z 2020-04-01 20:15.30 Binder: Waiting on event stream (phase: building) action=binder-start phase=event-stream
2020-04-01T20:15:31.0465511Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/runpy.py", line 86, in _run_code
2020-04-01T20:15:31.0465918Z 2020-04-01 20:15.30 Binder: Waiting on event stream (phase: building) action=binder-start phase=event-stream
2020-04-01T20:15:31.0466258Z     exec(code, run_globals)
2020-04-01T20:15:31.0466649Z 2020-04-01 20:15.30 Binder: Waiting on event stream (phase: building) action=binder-start phase=event-stream
2020-04-01T20:15:31.0467270Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/binderbot/cli.py", line 77, in <module>
2020-04-01T20:15:31.0467655Z 2020-04-01 20:15.30 Binder: Waiting on event stream (phase: building) action=binder-start phase=event-stream
2020-04-01T20:15:31.0467989Z     sys.exit(main())  # pragma: no cover
2020-04-01T20:15:31.0468525Z 2020-04-01 20:15.30 Binder: Waiting on event stream (phase: building) action=binder-start phase=event-stream
2020-04-01T20:15:31.0468979Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
2020-04-01T20:15:31.0469131Z     return self.main(*args, **kwargs)
2020-04-01T20:15:31.0469472Z 2020-04-01 20:15.30 Binder: Build timeout          action=binder-start duration=300.040256441 phase=failed
2020-04-01T20:15:31.0470410Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/click/core.py", line 782, in main
2020-04-01T20:15:31.0470598Z     rv = self.invoke(ctx)
2020-04-01T20:15:31.0471032Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
2020-04-01T20:15:31.0471195Z     return ctx.invoke(self.callback, **ctx.params)
2020-04-01T20:15:31.0471571Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
2020-04-01T20:15:31.0471725Z     return callback(*args, **kwargs)
2020-04-01T20:15:31.0472101Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/binderbot/cli.py", line 17, in wrapper
2020-04-01T20:15:31.0472258Z     return loop.run_until_complete(f(*args, **kwargs))
2020-04-01T20:15:31.0472446Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2020-04-01T20:15:31.0472588Z     return future.result()
2020-04-01T20:15:31.0472964Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/binderbot/cli.py", line 49, in main
2020-04-01T20:15:31.0473114Z     await jovyan.start_binder()
2020-04-01T20:15:31.0473506Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/binderbot/binderbot.py", line 84, in start_binder
2020-04-01T20:15:31.0473849Z     raise OperationError()
2020-04-01T20:15:31.0474210Z binderbot.binderbot.OperationError
```

**Comment by TomAugspurger** [comment]
It's https://github.com/pangeo-gallery/binderbot/blob/master/binderbot/binderbot.py#L55

Would be nice to bump that by default, or make it configurable through the content repo's config.
