### ISSUE TITLE
ClientResponseError from binderbot

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-gallery/binderbot#6]
From this GH action run: https://github.com/TomAugspurger/pangeo-dask-gateway/runs/571300961

```
2020-04-08T16:03:33.2277937Z 2020-04-08 16:03.33 Binder: Waiting on event stream (phase: launching) action=binder-start phase=event-stream
2020-04-08T16:06:57.9329437Z 2020-04-08 16:06.57 Binder: Got token and url (https://hub.binder.pangeo.io/user/tomaugspurger-p-eo-dask-gateway-3aq8of78/) action=binder-ready duration=212.04667152400003 phase=build-token
2020-04-08T16:06:57.9332526Z 2020-04-08 16:06.57 Kernel: Starting               action=kernel-start phase=start
2020-04-08T16:06:58.1466490Z 2020-04-08 16:06.58 Kernel: Started                action=kernel-start phase=complete
2020-04-08T16:06:58.1466926Z âœ… Binder and kernel started successfully.
2020-04-08T16:06:58.2965787Z /opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/binderbot/cli.py:14: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
2020-04-08T16:06:58.2966044Z   f = asyncio.coroutine(f)
2020-04-08T16:06:58.2966176Z Traceback (most recent call last):
2020-04-08T16:06:58.2967271Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/runpy.py", line 193, in _run_module_as_main
2020-04-08T16:06:58.2967469Z     return _run_code(code, main_globals, None,
2020-04-08T16:06:58.2967653Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/runpy.py", line 86, in _run_code
2020-04-08T16:06:58.2968366Z     exec(code, run_globals)
2020-04-08T16:06:58.2969049Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/binderbot/cli.py", line 77, in <module>
2020-04-08T16:06:58.2969215Z     sys.exit(main())  # pragma: no cover
2020-04-08T16:06:58.2969659Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
2020-04-08T16:06:58.2969824Z     return self.main(*args, **kwargs)
2020-04-08T16:06:58.2970258Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/click/core.py", line 782, in main
2020-04-08T16:06:58.2970408Z     rv = self.invoke(ctx)
2020-04-08T16:06:58.2970818Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
2020-04-08T16:06:58.2970980Z     return ctx.invoke(self.callback, **ctx.params)
2020-04-08T16:06:58.2971415Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
2020-04-08T16:06:58.2971580Z     return callback(*args, **kwargs)
2020-04-08T16:06:58.2972011Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/binderbot/cli.py", line 17, in wrapper
2020-04-08T16:06:58.2972160Z     return loop.run_until_complete(f(*args, **kwargs))
2020-04-08T16:06:58.2972338Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2020-04-08T16:06:58.2972487Z     return future.result()
2020-04-08T16:06:58.2972982Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/binderbot/cli.py", line 56, in main
2020-04-08T16:06:58.2973140Z     await jovyan.upload_local_notebook(fname)
2020-04-08T16:06:58.2973624Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/binderbot/binderbot.py", line 286, in upload_local_notebook
2020-04-08T16:06:58.2973789Z     await self.put_contents(notebook_filename, nb)
2020-04-08T16:06:58.2974240Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/binderbot/binderbot.py", line 150, in put_contents
2020-04-08T16:06:58.2974377Z     resp.raise_for_status()
2020-04-08T16:06:58.2974845Z   File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 941, in raise_for_status
2020-04-08T16:06:58.2975020Z     raise ClientResponseError(
2020-04-08T16:06:58.2975832Z aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://hub.binder.pangeo.io/user/tomaugspurger-p-eo-dask-gateway-3aq8of78/api/contents/using-dask-gateway.ipynb')
2020-04-08T16:06:58.3405683Z âŒ›ï¸ Uploading using-dask-gateway.ipynb...
2020-04-08T16:06:58.3414955Z ##[error]Process completed with exit code 1.
```

(cc @rabernat)

**Comment by TomAugspurger** [comment]
using-dask-gateway.ipynb is the notebook in https://github.com/TomAugspurger/pangeo-dask-gateway.

**Comment by rabernat** [comment]
My hunch is that the error is because the notebook already exists in the binder. I'm trying to verify that now.

**Comment by TomAugspurger** [comment]
That sounds plausible. The first time this ran binderbot hit a timeout
error.

**Comment by rabernat** [comment]
Nope, I think not :( I'm puzzled.

**Comment by rabernat** [comment]
So running on a different binder does overcome that error:

```
python -m binderbot.cli  --binder-url https://binder.pangeo.io 
    --repo pangeo-gallery/default-binder --ref master *.ipynb
```

So it's something about this specific binder that is not working.

**Comment by rabernat** [comment]
In #7 I added a few things to provide a bit of extra error handling.

**Comment by rabernat** [comment]
At this point might be useful to have @yuvipanda weigh in. I really don't know why the jupyter notebook server API is returning this 400 error.

**Comment by TomAugspurger** [comment]
Here's the logs from the pod created for binderbot. Sorry for not thinking to get them earlier

```
2020-04-08T19:50:30.288353204Z [I 19:50:30.288 LabApp] http://jupyter-tomaugspurger-2dp-2deo-2ddask-2dgateway-2dy75zvygd:8888/user/tomaugspurger-p-eo-dask-gateway-y75zvygd/?token=...
 E 
2020-04-08T19:50:30.288407480Z [I 19:50:30.288 LabApp]  or http://127.0.0.1:8888/user/tomaugspurger-p-eo-dask-gateway-y75zvygd/?token=...
 E 
2020-04-08T19:50:30.288543435Z [I 19:50:30.288 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
 E 
2020-04-08T19:50:30.292885295Z [W 19:50:30.292 LabApp] No web browser found: could not locate runnable browser.
 E 
2020-04-08T19:50:30.295712177Z [I 19:50:30.295 LabApp] 302 GET /user/tomaugspurger-p-eo-dask-gateway-y75zvygd/ (10.48.16.5) 0.87ms
 E 
2020-04-08T19:50:39.498558548Z [I 19:50:39.497 LabApp] Kernel started: ba570be8-8cf8-4d5f-ba99-f21f1a0e9fa4
 E 
2020-04-08T19:50:39.555499927Z [I 19:50:39.554 LabApp] Saving file at /using-dask-gateway.ipynb
 E 
2020-04-08T19:50:39.555543761Z [W 19:50:39.555 LabApp] 400 PUT /user/tomaugspurger-p-eo-dask-gateway-y75zvygd/api/contents/using-dask-gateway.ipynb (52.254.19.13): No file type provided
 E 
2020-04-08T19:50:39.555916737Z [W 19:50:39.555 LabApp] No file type provided
 E 
2020-04-08T19:50:39.556497106Z [W 19:50:39.556 LabApp] 400 PUT /user/tomaugspurger-p-eo-dask-gateway-y75zvygd/api/contents/using-dask-gateway.ipynb (52.254.19.13) 2.72ms referer=None
 E 

```

"No file type provided" seems to be the issue?

**Comment by rabernat** [comment]
> "No file type provided" seems to be the issue?

This is very useful information. It must be a Jupyter version issue. I suspect a more recent release requires some extra headers related to file type. But if so, this is not documented in the API docs:
https://github.com/jupyter/jupyter/wiki/Jupyter-Notebook-Server-API#Notebook-and-file-contents-API

**Comment by rabernat** [comment]
Anyone have any ideas on this?

**Comment by TomAugspurger** [comment]
Planning to investigate it today. I'll get the jupyter / notebook / hub versions.

I have access to the logs & admin token of the binder so I'm best situated to debug it.

**Comment by TomAugspurger** [comment]
Well, this may have just been user error. I had `binder_repo` pointing to my own repo rather than `pangeo-gallery/default-binder`. https://github.com/TomAugspurger/pangeo-dask-gateway/commit/dd3bf361fb58d2737374341f37761dd42758bbe1, things get past the build stage: https://github.com/TomAugspurger/pangeo-dask-gateway/runs/583090684.

Before fixing that, I confirmed that


```diff
diff --git a/binderbot/binderbot.py b/binderbot/binderbot.py
index 55c28c0..ea25ba8 100644
--- a/binderbot/binderbot.py
+++ b/binderbot/binderbot.py
@@ -144,7 +144,7 @@ class BinderUser:
 
     async def put_contents(self, path, nb_data):
         headers = {'Authorization': f'token {self.token}'}
-        data = {'content': nb_data}
+        data = {'content': nb_data, "type": "notebook"}
         resp = await self.session.put(self.notebook_url / 'api/contents' / path,
                                       json=data, headers=headers)
         resp.raise_for_status()
```

fixed the issue. We might want that regardless?

---

Now failing at


```
Run curl -f https://pangeo-gallery-bot.herokuapp.com/gallery/submodule-dispatch/TomAugspurger/pangeo-dask-gateway
  curl -f https://pangeo-gallery-bot.herokuapp.com/gallery/submodule-dispatch/TomAugspurger/pangeo-dask-gateway
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.2/x64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (22) The requested URL returned error: 500 Internal Server Error
```.

Does this need to be added as a git submodule first?

**Comment by rabernat** [comment]
> I had `binder_repo` pointing to my own repo rather than `pangeo-gallery/default-binder`

We should be able to support the case where the binder config lives in the same repo as the notebooks. It's easier if the binder config at least lives in a separate branch, however.

Would love a PR to add the `"type": "notebook"` header to `put_contents`.
